@startuml
class Bullet {
    -OnCollisionEnter(Collision collision)
}

class Enemy {
    +ApplyDamageToShadow()
    +ApplyDamageToGigas()
    +ApplyDamageToDarkInferno()
}

Bullet --> Enemy
@enduml